# -*- coding: utf-8 -*-
"""[A090E112_1005.ipynb」的副本

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J_RiSLxMkjaQLOZA6eUAXeb0PavIVu6b

# HASH 雜湊函數
- md5
- sha1



- linux指令
- md5sum
- Colab使用方式 : !md5sum 檔案名稱
"""

!md5sum --help

!echo YUKI > 1005.txt

!cat 1005.txt

!md5sum 1005.txt

!echo  yuki > 1005a.txt

!cat 1005a.txt

!md5sum 1005a.txt